name: Release

on: workflow_dispatch

jobs:
  test:
    name: Run tests
    uses: ./.github/workflows/test.yml

  release:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update NPM
        run: npm i -g npm@8.3.1 # avoid npm@8.4 win32 bug

      - name: Install dependencies
        run: npm i

      - name: Semantic release
        uses: codfish/semantic-release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
          GIT_AUTHOR_NAME: '${{ github.actor }}'
          GIT_COMMITTER_NAME: '${{ github.actor }}'
