name: Release

on:
  workflow_dispatch:
  schedule:
    - cron: '00 00 * * *'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Install dependencies
        run: npm i

      - name: Build
        run: npm run build

      - name: Semantic release
        uses: codfish/semantic-release-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
          GIT_AUTHOR_NAME: '${{ github.actor }}'
          GIT_COMMITTER_NAME: '${{ github.actor }}'
